zero size common blocks (#965)
Common blocks without explicit initialization are initialized with an
mlir::VectorType initializer, which must have a strictly positive size:

  real nada(1:0)
  common /empty/ nada

  fir.global common @_QBempty(dense<0> : vector<0xi8>) : !fir.array<0xi8>

  error: vector types must have positive constant sizes

An alternative is to instead initialize with a fir::SequenceType, but
that leads to a tco error:

  fir.global common @_QBempty : !fir.array<0xi8> {
    %0 = fir.undefined !fir.array<0xi8>
    fir.has_value %0 : !fir.array<0xi8>
  }

  'common' global must have a zero initializer!
  [0 x i8]* @_QBempty
  error: could not emit LLVM-IR

Work around these issues by forcing zero size common blocks to have one
byte:

  fir.global common @_QBempty(dense<0> : vector<1xi8>) : !fir.array<1xi8>

Note:  There is an additional front end bug where most zero size arrays
are incorrectly given non-zero size.  This additional bug needs to be
addressed to allow correct compilation of common blocks containing
those arrays.