Add missing build-time dependency in FrontendTool CMake
FrontendTool cpp files use headers from lib/Frontend that themselves
uses MLIR headers containing tablegen generated content.

In parallel builds, if FrontendTool is built before the headers required
by Frontend, the build may fail with message like:

```
Building CXX object tools/flang/lib/FrontendTool/CMakeFiles/obj.flangFrontendTool.dir/ExecuteCompilerInvocation.cpp.o
In file included from mlir/include/mlir/IR/BuiltinTypes.h:13,
                 from mlir/include/mlir/IR/FunctionSupport.h:17,
                 from mlir/include/mlir/IR/BuiltinOps.h:16,
                 from flang/include/flang/Frontend/CompilerInstance.h:11,
                 from flang/lib/FrontendTool/ExecuteCompilerInvocation.cpp:14:
mlir/include/mlir/IR/SubElementInterfaces.h:21:10: fatal error: mlir/IR/SubElementAttrInterfaces.h.inc: No such file or directory
   21 | #include "mlir/IR/SubElementAttrInterfaces.h.inc"
      |
```

Make Frontend a dependency of FrontendTool so that all the headers
from Frontend are ready to be used when building FrontendTool.