Fix FirOps.cpp build error after PR 1219
After https://github.com/flang-compiler/f18-llvm-project/pull/1219 clang 9 emits error:

flang/lib/Optimizer/Dialect/FIROps.cpp:1410:10: warning: local variable 'attrs' will be copied despite being returned by name [-Wreturn-std-move]
  return attrs;
flang/lib/Optimizer/Dialect/FIROps.cpp:1410:10: error: no viable conversion from returned value of type 'SmallVector<[...], 2>' to function return type 'SmallVector<[...], (default) CalculateSmallVectorDefaultInlinedElements<T>::value aka 6>'
  return attrs;

No fix is needed in upstream LLVM since fir::FieldIndexOp::getAttributes is not there.